// <auto-generated />
using System;
using CaseStudy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaseStudy.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201114184757_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CaseStudy.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("095d7240-e0d9-40c9-91d0-01219e432994"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 331, DateTimeKind.Local).AddTicks(2959),
                            Description = "Popis k produktu č. 1",
                            ImgUri = "https://cdn.alza.cz/Foto/1",
                            Name = "Produkt 1",
                            Price = 60934.71m
                        },
                        new
                        {
                            Id = new Guid("b20cc21c-bd7b-4b4d-adef-7a803ba0822e"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2742),
                            Description = "Popis k produktu č. 2",
                            ImgUri = "https://cdn.alza.cz/Foto/2",
                            Name = "Produkt 2",
                            Price = 10984.36m
                        },
                        new
                        {
                            Id = new Guid("c49f6761-88f7-4435-a314-57b4a0dd0ad2"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2861),
                            Description = "Popis k produktu č. 3",
                            ImgUri = "https://cdn.alza.cz/Foto/3",
                            Name = "Produkt 3",
                            Price = 36912.23m
                        },
                        new
                        {
                            Id = new Guid("f19a0026-8a12-49e8-b98a-ab1f51741743"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2872),
                            Description = "Popis k produktu č. 4",
                            ImgUri = "https://cdn.alza.cz/Foto/4",
                            Name = "Produkt 4",
                            Price = 64143.43m
                        },
                        new
                        {
                            Id = new Guid("bc528fe9-267c-4737-bd71-76b051965e25"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2879),
                            Description = "Popis k produktu č. 5",
                            ImgUri = "https://cdn.alza.cz/Foto/5",
                            Name = "Produkt 5",
                            Price = 94813.25m
                        },
                        new
                        {
                            Id = new Guid("87bbbbe4-2cea-423b-ab4a-644dc12dd5d9"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2891),
                            Description = "Popis k produktu č. 6",
                            ImgUri = "https://cdn.alza.cz/Foto/6",
                            Name = "Produkt 6",
                            Price = 33958.95m
                        },
                        new
                        {
                            Id = new Guid("cf4cf9c0-8e6e-43ad-8292-6b6acffc0299"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2897),
                            Description = "Popis k produktu č. 7",
                            ImgUri = "https://cdn.alza.cz/Foto/7",
                            Name = "Produkt 7",
                            Price = 84494.96m
                        },
                        new
                        {
                            Id = new Guid("af8a27d3-55b7-49eb-9c5d-6371929d49d7"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2915),
                            Description = "Popis k produktu č. 8",
                            ImgUri = "https://cdn.alza.cz/Foto/8",
                            Name = "Produkt 8",
                            Price = 45288.2m
                        },
                        new
                        {
                            Id = new Guid("42e26b81-b41e-4ce3-a364-9d34c05fa5e9"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2922),
                            Description = "Popis k produktu č. 9",
                            ImgUri = "https://cdn.alza.cz/Foto/9",
                            Name = "Produkt 9",
                            Price = 86020.05m
                        },
                        new
                        {
                            Id = new Guid("6db72a0f-d317-4136-8465-b986b03d9009"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2930),
                            Description = "Popis k produktu č. 10",
                            ImgUri = "https://cdn.alza.cz/Foto/10",
                            Name = "Produkt 10",
                            Price = 17357.52m
                        },
                        new
                        {
                            Id = new Guid("893cc0ab-0d0d-4800-9b85-34e94adb477d"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2937),
                            Description = "Popis k produktu č. 11",
                            ImgUri = "https://cdn.alza.cz/Foto/11",
                            Name = "Produkt 11",
                            Price = 91160.92m
                        },
                        new
                        {
                            Id = new Guid("03473e4b-8ac6-4416-8a8d-9c7fd8528bf5"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2944),
                            Description = "Popis k produktu č. 12",
                            ImgUri = "https://cdn.alza.cz/Foto/12",
                            Name = "Produkt 12",
                            Price = 33775.17m
                        },
                        new
                        {
                            Id = new Guid("88859109-ee16-4c6d-899f-9f9194e34f6c"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2950),
                            Description = "Popis k produktu č. 13",
                            ImgUri = "https://cdn.alza.cz/Foto/13",
                            Name = "Produkt 13",
                            Price = 50693.05m
                        },
                        new
                        {
                            Id = new Guid("02abee1d-cc09-4846-a677-7d493fe28d50"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2956),
                            Description = "Popis k produktu č. 14",
                            ImgUri = "https://cdn.alza.cz/Foto/14",
                            Name = "Produkt 14",
                            Price = 18168.03m
                        },
                        new
                        {
                            Id = new Guid("41df05bc-171c-4788-8eef-b36e03802785"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2963),
                            Description = "Popis k produktu č. 15",
                            ImgUri = "https://cdn.alza.cz/Foto/15",
                            Name = "Produkt 15",
                            Price = 90167.46m
                        },
                        new
                        {
                            Id = new Guid("039659c0-ccca-42d2-aaba-f45895e510b3"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(2972),
                            Description = "Popis k produktu č. 16",
                            ImgUri = "https://cdn.alza.cz/Foto/16",
                            Name = "Produkt 16",
                            Price = 2021.96m
                        },
                        new
                        {
                            Id = new Guid("bee184f4-ebd0-4be5-9de8-cbe74cf65758"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3006),
                            Description = "Popis k produktu č. 17",
                            ImgUri = "https://cdn.alza.cz/Foto/17",
                            Name = "Produkt 17",
                            Price = 81959.5m
                        },
                        new
                        {
                            Id = new Guid("c8da26c9-0ae5-40ba-9262-f83033d5fd60"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3014),
                            Description = "Popis k produktu č. 18",
                            ImgUri = "https://cdn.alza.cz/Foto/18",
                            Name = "Produkt 18",
                            Price = 68259.24m
                        },
                        new
                        {
                            Id = new Guid("f89cfc68-03d9-4f0c-8e05-f6c1b752ced2"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3020),
                            Description = "Popis k produktu č. 19",
                            ImgUri = "https://cdn.alza.cz/Foto/19",
                            Name = "Produkt 19",
                            Price = 38910.3m
                        },
                        new
                        {
                            Id = new Guid("f8d5da1c-ae35-4c2f-8b31-8e8296618129"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3027),
                            Description = "Popis k produktu č. 20",
                            ImgUri = "https://cdn.alza.cz/Foto/20",
                            Name = "Produkt 20",
                            Price = 52370.34m
                        },
                        new
                        {
                            Id = new Guid("ec91b5fb-3f39-41bc-be78-cfb4e560b43a"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3034),
                            Description = "Popis k produktu č. 21",
                            ImgUri = "https://cdn.alza.cz/Foto/21",
                            Name = "Produkt 21",
                            Price = 85846.5m
                        },
                        new
                        {
                            Id = new Guid("85e3cf3d-87d8-4525-a268-ad8c9a860c1a"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3040),
                            Description = "Popis k produktu č. 22",
                            ImgUri = "https://cdn.alza.cz/Foto/22",
                            Name = "Produkt 22",
                            Price = 52973.07m
                        },
                        new
                        {
                            Id = new Guid("515abff6-9473-41dc-99cc-7131a3fc474d"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3046),
                            Description = "Popis k produktu č. 23",
                            ImgUri = "https://cdn.alza.cz/Foto/23",
                            Name = "Produkt 23",
                            Price = 669.51m
                        },
                        new
                        {
                            Id = new Guid("ece680e9-733f-46c6-b623-1f8b2957eae9"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3056),
                            Description = "Popis k produktu č. 24",
                            ImgUri = "https://cdn.alza.cz/Foto/24",
                            Name = "Produkt 24",
                            Price = 39244.35m
                        },
                        new
                        {
                            Id = new Guid("0afaea95-2cd4-482c-a6ee-d5b46b3b524a"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3062),
                            Description = "Popis k produktu č. 25",
                            ImgUri = "https://cdn.alza.cz/Foto/25",
                            Name = "Produkt 25",
                            Price = 9954.53m
                        },
                        new
                        {
                            Id = new Guid("318b2395-8cd9-45da-8fad-d00f0df8e4fb"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3069),
                            Description = "Popis k produktu č. 26",
                            ImgUri = "https://cdn.alza.cz/Foto/26",
                            Name = "Produkt 26",
                            Price = 83979.3m
                        },
                        new
                        {
                            Id = new Guid("5188a139-2d75-4ddd-bbc7-530937664fb7"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3075),
                            Description = "Popis k produktu č. 27",
                            ImgUri = "https://cdn.alza.cz/Foto/27",
                            Name = "Produkt 27",
                            Price = 66779.59m
                        },
                        new
                        {
                            Id = new Guid("b9dd3b68-8f07-4726-ba9a-b2da27c90267"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3082),
                            Description = "Popis k produktu č. 28",
                            ImgUri = "https://cdn.alza.cz/Foto/28",
                            Name = "Produkt 28",
                            Price = 10761.08m
                        },
                        new
                        {
                            Id = new Guid("8c14e86b-dd37-44bd-816a-9f797de01deb"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3089),
                            Description = "Popis k produktu č. 29",
                            ImgUri = "https://cdn.alza.cz/Foto/29",
                            Name = "Produkt 29",
                            Price = 58059.81m
                        },
                        new
                        {
                            Id = new Guid("940d9dd5-6b94-40ad-9e41-91ad9c80a3a1"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3095),
                            Description = "Popis k produktu č. 30",
                            ImgUri = "https://cdn.alza.cz/Foto/30",
                            Name = "Produkt 30",
                            Price = 94937.11m
                        },
                        new
                        {
                            Id = new Guid("3f5dde79-fc15-4d20-9ed0-82df0a30b9ba"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3102),
                            Description = "Popis k produktu č. 31",
                            ImgUri = "https://cdn.alza.cz/Foto/31",
                            Name = "Produkt 31",
                            Price = 14527.54m
                        },
                        new
                        {
                            Id = new Guid("4b84cfc1-5f58-4816-87d3-5c81d8760a88"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3110),
                            Description = "Popis k produktu č. 32",
                            ImgUri = "https://cdn.alza.cz/Foto/32",
                            Name = "Produkt 32",
                            Price = 75291.04m
                        },
                        new
                        {
                            Id = new Guid("2b6cde89-9405-4b8f-943b-154b0160919c"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3117),
                            Description = "Popis k produktu č. 33",
                            ImgUri = "https://cdn.alza.cz/Foto/33",
                            Name = "Produkt 33",
                            Price = 40846.63m
                        },
                        new
                        {
                            Id = new Guid("079768d7-566d-431e-a45d-4dae8ad435bc"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3124),
                            Description = "Popis k produktu č. 34",
                            ImgUri = "https://cdn.alza.cz/Foto/34",
                            Name = "Produkt 34",
                            Price = 96295.51m
                        },
                        new
                        {
                            Id = new Guid("3450aed9-9601-489d-b2b3-ccddc6aaadd6"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3136),
                            Description = "Popis k produktu č. 35",
                            ImgUri = "https://cdn.alza.cz/Foto/35",
                            Name = "Produkt 35",
                            Price = 66690.32m
                        },
                        new
                        {
                            Id = new Guid("e330b11a-f5e8-407d-a782-ab6bd6a299ef"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3143),
                            Description = "Popis k produktu č. 36",
                            ImgUri = "https://cdn.alza.cz/Foto/36",
                            Name = "Produkt 36",
                            Price = 96296.48m
                        },
                        new
                        {
                            Id = new Guid("16288937-b7e6-4905-9836-a9277fafdf4c"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3149),
                            Description = "Popis k produktu č. 37",
                            ImgUri = "https://cdn.alza.cz/Foto/37",
                            Name = "Produkt 37",
                            Price = 60215.32m
                        },
                        new
                        {
                            Id = new Guid("b9b91e33-a274-4f7a-ac48-66a0a18ebd67"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3156),
                            Description = "Popis k produktu č. 38",
                            ImgUri = "https://cdn.alza.cz/Foto/38",
                            Name = "Produkt 38",
                            Price = 76229.73m
                        },
                        new
                        {
                            Id = new Guid("9b5027ca-5eec-4950-9d95-691809662e6a"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3162),
                            Description = "Popis k produktu č. 39",
                            ImgUri = "https://cdn.alza.cz/Foto/39",
                            Name = "Produkt 39",
                            Price = 32070.72m
                        },
                        new
                        {
                            Id = new Guid("48afb1cb-48b5-45b3-9e3b-897f8dcb2d98"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3171),
                            Description = "Popis k produktu č. 40",
                            ImgUri = "https://cdn.alza.cz/Foto/40",
                            Name = "Produkt 40",
                            Price = 18411.08m
                        },
                        new
                        {
                            Id = new Guid("6d718676-6d85-4177-8939-428493b8ac8f"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3178),
                            Description = "Popis k produktu č. 41",
                            ImgUri = "https://cdn.alza.cz/Foto/41",
                            Name = "Produkt 41",
                            Price = 66166.05m
                        },
                        new
                        {
                            Id = new Guid("910be9f8-adce-4bc9-a422-91f321f3ff5e"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3184),
                            Description = "Popis k produktu č. 42",
                            ImgUri = "https://cdn.alza.cz/Foto/42",
                            Name = "Produkt 42",
                            Price = 96886.58m
                        },
                        new
                        {
                            Id = new Guid("61effdeb-b1ab-4b44-ad2f-65be8ea25b05"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3190),
                            Description = "Popis k produktu č. 43",
                            ImgUri = "https://cdn.alza.cz/Foto/43",
                            Name = "Produkt 43",
                            Price = 88928.7m
                        },
                        new
                        {
                            Id = new Guid("074b0ea0-d051-4b5f-a9be-f9307d651e1e"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3197),
                            Description = "Popis k produktu č. 44",
                            ImgUri = "https://cdn.alza.cz/Foto/44",
                            Name = "Produkt 44",
                            Price = 74553.2m
                        },
                        new
                        {
                            Id = new Guid("daa96732-085a-4bda-a2bd-8e9e075bcc78"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3203),
                            Description = "Popis k produktu č. 45",
                            ImgUri = "https://cdn.alza.cz/Foto/45",
                            Name = "Produkt 45",
                            Price = 76173.65m
                        },
                        new
                        {
                            Id = new Guid("bb6ccb61-cb90-4b63-8266-99e5e4d43068"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3209),
                            Description = "Popis k produktu č. 46",
                            ImgUri = "https://cdn.alza.cz/Foto/46",
                            Name = "Produkt 46",
                            Price = 18484.67m
                        },
                        new
                        {
                            Id = new Guid("4b2efe52-4f2e-464a-b028-384d3af8756c"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3216),
                            Description = "Popis k produktu č. 47",
                            ImgUri = "https://cdn.alza.cz/Foto/47",
                            Name = "Produkt 47",
                            Price = 86673.59m
                        },
                        new
                        {
                            Id = new Guid("6d9c8ea9-c3ea-406f-acef-4e1c9ef3fa55"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3224),
                            Description = "Popis k produktu č. 48",
                            ImgUri = "https://cdn.alza.cz/Foto/48",
                            Name = "Produkt 48",
                            Price = 14858.15m
                        },
                        new
                        {
                            Id = new Guid("03ebcb57-173e-4cda-8b83-bdd6d4c06eba"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3231),
                            Description = "Popis k produktu č. 49",
                            ImgUri = "https://cdn.alza.cz/Foto/49",
                            Name = "Produkt 49",
                            Price = 16935.03m
                        },
                        new
                        {
                            Id = new Guid("c679b254-02eb-407e-b679-2baadb185523"),
                            Created = new DateTime(2020, 11, 14, 19, 47, 57, 334, DateTimeKind.Local).AddTicks(3237),
                            Description = "Popis k produktu č. 50",
                            ImgUri = "https://cdn.alza.cz/Foto/50",
                            Name = "Produkt 50",
                            Price = 51899.2m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
