// <auto-generated />
using System;
using CaseStudy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaseStudy.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201115180327_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CaseStudy.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae96089b-861c-456e-8dea-f400206c55e5"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 224, DateTimeKind.Local).AddTicks(7945),
                            Description = "Popis k produktu č. 01",
                            ImgUri = "https://cdn.alza.cz/Foto/01",
                            Name = "Produkt 01",
                            Price = 35099.74m
                        },
                        new
                        {
                            Id = new Guid("92060adc-a1a9-48e6-bfa3-5f3561ec5038"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8333),
                            Description = "Popis k produktu č. 02",
                            ImgUri = "https://cdn.alza.cz/Foto/02",
                            Name = "Produkt 02",
                            Price = 65912.18m
                        },
                        new
                        {
                            Id = new Guid("580e3d21-03c1-4066-8620-f526ab1dc319"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8489),
                            Description = "Popis k produktu č. 03",
                            ImgUri = "https://cdn.alza.cz/Foto/03",
                            Name = "Produkt 03",
                            Price = 28853.94m
                        },
                        new
                        {
                            Id = new Guid("1bfca8d3-982e-4082-9d71-ed50f2b786fb"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8578),
                            Description = "Popis k produktu č. 04",
                            ImgUri = "https://cdn.alza.cz/Foto/04",
                            Name = "Produkt 04",
                            Price = 33009.97m
                        },
                        new
                        {
                            Id = new Guid("65d6c8e8-44e5-4d99-9c59-3b57e2ca2538"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8591),
                            Description = "Popis k produktu č. 05",
                            ImgUri = "https://cdn.alza.cz/Foto/05",
                            Name = "Produkt 05",
                            Price = 46399.45m
                        },
                        new
                        {
                            Id = new Guid("756998b5-a6f7-48d4-aa3e-c1bc15ebc9bd"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8611),
                            Description = "Popis k produktu č. 06",
                            ImgUri = "https://cdn.alza.cz/Foto/06",
                            Name = "Produkt 06",
                            Price = 99253.36m
                        },
                        new
                        {
                            Id = new Guid("f89ab00c-74e3-4a3e-aafe-dadfb8cd5a5c"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8637),
                            Description = "Popis k produktu č. 07",
                            ImgUri = "https://cdn.alza.cz/Foto/07",
                            Name = "Produkt 07",
                            Price = 86025.27m
                        },
                        new
                        {
                            Id = new Guid("91ccde14-0397-44a6-bf07-feb44a96c750"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8649),
                            Description = "Popis k produktu č. 08",
                            ImgUri = "https://cdn.alza.cz/Foto/08",
                            Name = "Produkt 08",
                            Price = 80637.27m
                        },
                        new
                        {
                            Id = new Guid("38b8d62d-8b70-4f2a-a43e-095d8fac008b"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8661),
                            Description = "Popis k produktu č. 09",
                            ImgUri = "https://cdn.alza.cz/Foto/09",
                            Name = "Produkt 09",
                            Price = 91526.92m
                        },
                        new
                        {
                            Id = new Guid("6f972903-fcef-4d85-bda1-02e3305507d9"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8676),
                            Description = "Popis k produktu č. 10",
                            ImgUri = "https://cdn.alza.cz/Foto/10",
                            Name = "Produkt 10",
                            Price = 55788.49m
                        },
                        new
                        {
                            Id = new Guid("8dc81956-e1ee-4c9a-8f3b-fd12be811f63"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8689),
                            Description = "Popis k produktu č. 11",
                            ImgUri = "https://cdn.alza.cz/Foto/11",
                            Name = "Produkt 11",
                            Price = 44979.29m
                        },
                        new
                        {
                            Id = new Guid("380d5716-d39e-4294-b20f-45deb8b6db3f"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8700),
                            Description = "Popis k produktu č. 12",
                            ImgUri = "https://cdn.alza.cz/Foto/12",
                            Name = "Produkt 12",
                            Price = 81102.73m
                        },
                        new
                        {
                            Id = new Guid("bb3b6094-3cbf-47d2-9ceb-4700c7de82d2"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8711),
                            Description = "Popis k produktu č. 13",
                            ImgUri = "https://cdn.alza.cz/Foto/13",
                            Name = "Produkt 13",
                            Price = 8212.36m
                        },
                        new
                        {
                            Id = new Guid("87bcd017-4d9d-4690-a03d-584f91d5b8a7"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8721),
                            Description = "Popis k produktu č. 14",
                            ImgUri = "https://cdn.alza.cz/Foto/14",
                            Name = "Produkt 14",
                            Price = 84459.28m
                        },
                        new
                        {
                            Id = new Guid("99c4dd87-ddd9-41ec-a315-c8b1f92673d9"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8735),
                            Description = "Popis k produktu č. 15",
                            ImgUri = "https://cdn.alza.cz/Foto/15",
                            Name = "Produkt 15",
                            Price = 44924.54m
                        },
                        new
                        {
                            Id = new Guid("ecb8c574-76dd-4858-8f0d-71e70d135be9"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8744),
                            Description = "Popis k produktu č. 16",
                            ImgUri = "https://cdn.alza.cz/Foto/16",
                            Name = "Produkt 16",
                            Price = 29797m
                        },
                        new
                        {
                            Id = new Guid("40093b65-45e6-47a3-aed6-b6c37b30a0dd"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8754),
                            Description = "Popis k produktu č. 17",
                            ImgUri = "https://cdn.alza.cz/Foto/17",
                            Name = "Produkt 17",
                            Price = 28066.87m
                        },
                        new
                        {
                            Id = new Guid("e0581e04-55bd-4271-95a8-156eddc435b8"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8766),
                            Description = "Popis k produktu č. 18",
                            ImgUri = "https://cdn.alza.cz/Foto/18",
                            Name = "Produkt 18",
                            Price = 48061.81m
                        },
                        new
                        {
                            Id = new Guid("0c48df1f-b5fe-427b-b68e-093ebf43c5ff"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8775),
                            Description = "Popis k produktu č. 19",
                            ImgUri = "https://cdn.alza.cz/Foto/19",
                            Name = "Produkt 19",
                            Price = 53821.3m
                        },
                        new
                        {
                            Id = new Guid("4b99c164-b2e3-4ea4-98b4-2b16c784d646"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8784),
                            Description = "Popis k produktu č. 20",
                            ImgUri = "https://cdn.alza.cz/Foto/20",
                            Name = "Produkt 20",
                            Price = 77551.07m
                        },
                        new
                        {
                            Id = new Guid("bd135a97-4a4a-4b94-aad5-c5689e49d3df"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8793),
                            Description = "Popis k produktu č. 21",
                            ImgUri = "https://cdn.alza.cz/Foto/21",
                            Name = "Produkt 21",
                            Price = 88149.62m
                        },
                        new
                        {
                            Id = new Guid("31239b9e-0ee2-4af7-bc48-a95c870ed8ab"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8803),
                            Description = "Popis k produktu č. 22",
                            ImgUri = "https://cdn.alza.cz/Foto/22",
                            Name = "Produkt 22",
                            Price = 80002.34m
                        },
                        new
                        {
                            Id = new Guid("11bf6a8f-5612-48f8-9a87-a464c505fb69"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8816),
                            Description = "Popis k produktu č. 23",
                            ImgUri = "https://cdn.alza.cz/Foto/23",
                            Name = "Produkt 23",
                            Price = 18195.79m
                        },
                        new
                        {
                            Id = new Guid("683b9c1d-d93a-43d2-8b7c-1c9700566069"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8825),
                            Description = "Popis k produktu č. 24",
                            ImgUri = "https://cdn.alza.cz/Foto/24",
                            Name = "Produkt 24",
                            Price = 92876.67m
                        },
                        new
                        {
                            Id = new Guid("55a857a8-fad5-4710-b27a-404127ee7ac2"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8835),
                            Description = "Popis k produktu č. 25",
                            ImgUri = "https://cdn.alza.cz/Foto/25",
                            Name = "Produkt 25",
                            Price = 52309.79m
                        },
                        new
                        {
                            Id = new Guid("1e094d42-8030-497d-a2ed-e22b9b212de2"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8845),
                            Description = "Popis k produktu č. 26",
                            ImgUri = "https://cdn.alza.cz/Foto/26",
                            Name = "Produkt 26",
                            Price = 86255.74m
                        },
                        new
                        {
                            Id = new Guid("6d8403ec-b5f2-4b34-b940-6a84055021f4"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8903),
                            Description = "Popis k produktu č. 27",
                            ImgUri = "https://cdn.alza.cz/Foto/27",
                            Name = "Produkt 27",
                            Price = 383.99m
                        },
                        new
                        {
                            Id = new Guid("0fc10d5f-5411-4fed-a236-865e428a9633"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8916),
                            Description = "Popis k produktu č. 28",
                            ImgUri = "https://cdn.alza.cz/Foto/28",
                            Name = "Produkt 28",
                            Price = 3662.9m
                        },
                        new
                        {
                            Id = new Guid("8e024027-5568-411d-936e-77776f7e9cd3"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8926),
                            Description = "Popis k produktu č. 29",
                            ImgUri = "https://cdn.alza.cz/Foto/29",
                            Name = "Produkt 29",
                            Price = 49101.86m
                        },
                        new
                        {
                            Id = new Guid("7fddc55c-0419-48ad-9dda-0637e2419c03"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8936),
                            Description = "Popis k produktu č. 30",
                            ImgUri = "https://cdn.alza.cz/Foto/30",
                            Name = "Produkt 30",
                            Price = 754.48m
                        },
                        new
                        {
                            Id = new Guid("dc3a5509-4029-4797-bf00-9cd83ebf3c39"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8950),
                            Description = "Popis k produktu č. 31",
                            ImgUri = "https://cdn.alza.cz/Foto/31",
                            Name = "Produkt 31",
                            Price = 47151.69m
                        },
                        new
                        {
                            Id = new Guid("548fda38-8035-4f68-9cd2-51c8e92e9568"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8959),
                            Description = "Popis k produktu č. 32",
                            ImgUri = "https://cdn.alza.cz/Foto/32",
                            Name = "Produkt 32",
                            Price = 15662.59m
                        },
                        new
                        {
                            Id = new Guid("1e05d426-1968-4306-8f11-137121d00c32"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8969),
                            Description = "Popis k produktu č. 33",
                            ImgUri = "https://cdn.alza.cz/Foto/33",
                            Name = "Produkt 33",
                            Price = 23099.12m
                        },
                        new
                        {
                            Id = new Guid("ccd60290-9912-4cbc-8593-fc216ee47ee9"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8983),
                            Description = "Popis k produktu č. 34",
                            ImgUri = "https://cdn.alza.cz/Foto/34",
                            Name = "Produkt 34",
                            Price = 57111.71m
                        },
                        new
                        {
                            Id = new Guid("7a3a0c65-9168-4336-90a3-ce3d2bd18c93"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(8994),
                            Description = "Popis k produktu č. 35",
                            ImgUri = "https://cdn.alza.cz/Foto/35",
                            Name = "Produkt 35",
                            Price = 60610.07m
                        },
                        new
                        {
                            Id = new Guid("c146c8e9-a0f6-407f-84e4-7a916a62c8a8"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9005),
                            Description = "Popis k produktu č. 36",
                            ImgUri = "https://cdn.alza.cz/Foto/36",
                            Name = "Produkt 36",
                            Price = 22099.67m
                        },
                        new
                        {
                            Id = new Guid("2c8bd5bb-fece-4971-9a3a-dad255d6e17b"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9015),
                            Description = "Popis k produktu č. 37",
                            ImgUri = "https://cdn.alza.cz/Foto/37",
                            Name = "Produkt 37",
                            Price = 11602.97m
                        },
                        new
                        {
                            Id = new Guid("5ba87061-8cf7-4518-8b2e-059a6e1bbb37"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9025),
                            Description = "Popis k produktu č. 38",
                            ImgUri = "https://cdn.alza.cz/Foto/38",
                            Name = "Produkt 38",
                            Price = 46492.11m
                        },
                        new
                        {
                            Id = new Guid("c9720edf-5ce1-4822-aafb-25f88aa81260"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9040),
                            Description = "Popis k produktu č. 39",
                            ImgUri = "https://cdn.alza.cz/Foto/39",
                            Name = "Produkt 39",
                            Price = 16926.86m
                        },
                        new
                        {
                            Id = new Guid("a38e4a4d-bdb2-4295-bdba-f1ef6d5b3d7c"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9050),
                            Description = "Popis k produktu č. 40",
                            ImgUri = "https://cdn.alza.cz/Foto/40",
                            Name = "Produkt 40",
                            Price = 53794.11m
                        },
                        new
                        {
                            Id = new Guid("2a265986-0eba-478c-b062-f9e669471f38"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9060),
                            Description = "Popis k produktu č. 41",
                            ImgUri = "https://cdn.alza.cz/Foto/41",
                            Name = "Produkt 41",
                            Price = 94000.87m
                        },
                        new
                        {
                            Id = new Guid("7ac50599-3db6-4d18-8708-4d46ff252271"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9071),
                            Description = "Popis k produktu č. 42",
                            ImgUri = "https://cdn.alza.cz/Foto/42",
                            Name = "Produkt 42",
                            Price = 45248.97m
                        },
                        new
                        {
                            Id = new Guid("019f7156-8955-464d-9b64-c99c99099d33"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9083),
                            Description = "Popis k produktu č. 43",
                            ImgUri = "https://cdn.alza.cz/Foto/43",
                            Name = "Produkt 43",
                            Price = 23582.46m
                        },
                        new
                        {
                            Id = new Guid("13b5d9af-cbc8-4985-bec8-2f31a8396015"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9093),
                            Description = "Popis k produktu č. 44",
                            ImgUri = "https://cdn.alza.cz/Foto/44",
                            Name = "Produkt 44",
                            Price = 52929.85m
                        },
                        new
                        {
                            Id = new Guid("39f94f8d-a557-456e-9780-063ff86bc824"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9104),
                            Description = "Popis k produktu č. 45",
                            ImgUri = "https://cdn.alza.cz/Foto/45",
                            Name = "Produkt 45",
                            Price = 70794.1m
                        },
                        new
                        {
                            Id = new Guid("b1cf0749-a6c8-443b-925a-be3dd92e9888"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9114),
                            Description = "Popis k produktu č. 46",
                            ImgUri = "https://cdn.alza.cz/Foto/46",
                            Name = "Produkt 46",
                            Price = 43659.17m
                        },
                        new
                        {
                            Id = new Guid("c6780881-13c3-429a-bd33-81fd8e5986cc"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9126),
                            Description = "Popis k produktu č. 47",
                            ImgUri = "https://cdn.alza.cz/Foto/47",
                            Name = "Produkt 47",
                            Price = 31837.15m
                        },
                        new
                        {
                            Id = new Guid("8b5e05f6-5837-4072-95f6-fd6a5c9d2e97"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9135),
                            Description = "Popis k produktu č. 48",
                            ImgUri = "https://cdn.alza.cz/Foto/48",
                            Name = "Produkt 48",
                            Price = 26659.91m
                        },
                        new
                        {
                            Id = new Guid("0e8cd973-6134-4319-8d54-3fc319f513a9"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9144),
                            Description = "Popis k produktu č. 49",
                            ImgUri = "https://cdn.alza.cz/Foto/49",
                            Name = "Produkt 49",
                            Price = 7153.18m
                        },
                        new
                        {
                            Id = new Guid("f0a3190c-81df-43a1-8407-162b17b278ac"),
                            Created = new DateTime(2020, 11, 15, 19, 3, 27, 228, DateTimeKind.Local).AddTicks(9223),
                            Description = "Popis k produktu č. 50",
                            ImgUri = "https://cdn.alza.cz/Foto/50",
                            Name = "Produkt 50",
                            Price = 97871.07m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
