// <auto-generated />
using System;
using CaseStudy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaseStudy.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201116133045_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CaseStudy.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb2221b4-f761-4228-b354-a6fb53ab2be0"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 261, DateTimeKind.Local).AddTicks(8864),
                            Description = "The description of product 01",
                            ImgUri = "https://cdn.alza.cz/Foto/01",
                            Name = "Product 01",
                            Price = 51221.56m
                        },
                        new
                        {
                            Id = new Guid("2356ba20-6d8e-444f-8625-062165c6956f"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(7833),
                            Description = "The description of product 02",
                            ImgUri = "https://cdn.alza.cz/Foto/02",
                            Name = "Product 02",
                            Price = 85859.71m
                        },
                        new
                        {
                            Id = new Guid("57f47587-2d03-4b4c-a463-d277de0abaa3"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(7949),
                            Description = "The description of product 03",
                            ImgUri = "https://cdn.alza.cz/Foto/03",
                            Name = "Product 03",
                            Price = 85293.5m
                        },
                        new
                        {
                            Id = new Guid("a5f05e43-04dd-4d00-9bde-40e48d607640"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(7961),
                            Description = "The description of product 04",
                            ImgUri = "https://cdn.alza.cz/Foto/04",
                            Name = "Product 04",
                            Price = 6140.19m
                        },
                        new
                        {
                            Id = new Guid("7c4494b8-dc6e-4780-8427-4eee093aa1c2"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(7967),
                            Description = "The description of product 05",
                            ImgUri = "https://cdn.alza.cz/Foto/05",
                            Name = "Product 05",
                            Price = 44674.33m
                        },
                        new
                        {
                            Id = new Guid("942abd0e-34fe-483d-a093-accd8c189272"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(7979),
                            Description = "The description of product 06",
                            ImgUri = "https://cdn.alza.cz/Foto/06",
                            Name = "Product 06",
                            Price = 7103.46m
                        },
                        new
                        {
                            Id = new Guid("a986af61-7164-40a3-a845-e82dc347c32a"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(7986),
                            Description = "The description of product 07",
                            ImgUri = "https://cdn.alza.cz/Foto/07",
                            Name = "Product 07",
                            Price = 34883.71m
                        },
                        new
                        {
                            Id = new Guid("4f6437d2-9c86-4602-8299-e1cab435ee20"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8007),
                            Description = "The description of product 08",
                            ImgUri = "https://cdn.alza.cz/Foto/08",
                            Name = "Product 08",
                            Price = 81248.83m
                        },
                        new
                        {
                            Id = new Guid("91c03e1f-3951-42b7-8ce0-39beee0763c8"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8014),
                            Description = "The description of product 09",
                            ImgUri = "https://cdn.alza.cz/Foto/09",
                            Name = "Product 09",
                            Price = 98240.26m
                        },
                        new
                        {
                            Id = new Guid("f03245cb-dfc8-46ac-b647-c9edda223272"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8023),
                            Description = "The description of product 10",
                            ImgUri = "https://cdn.alza.cz/Foto/10",
                            Name = "Product 10",
                            Price = 43335.78m
                        },
                        new
                        {
                            Id = new Guid("e748adc3-90d2-4aef-9036-4d387f1dd843"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8030),
                            Description = "The description of product 11",
                            ImgUri = "https://cdn.alza.cz/Foto/11",
                            Name = "Product 11",
                            Price = 52767.85m
                        },
                        new
                        {
                            Id = new Guid("b4dc2274-32e3-415b-b36f-6b105079c9f4"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8099),
                            Description = "The description of product 12",
                            ImgUri = "https://cdn.alza.cz/Foto/12",
                            Name = "Product 12",
                            Price = 29367.98m
                        },
                        new
                        {
                            Id = new Guid("7eb1b076-c36c-4325-9fdd-2fc69b1d24d8"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8106),
                            Description = "The description of product 13",
                            ImgUri = "https://cdn.alza.cz/Foto/13",
                            Name = "Product 13",
                            Price = 99585.17m
                        },
                        new
                        {
                            Id = new Guid("847ab9b1-be17-4ba4-9dd0-edfad7394516"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8112),
                            Description = "The description of product 14",
                            ImgUri = "https://cdn.alza.cz/Foto/14",
                            Name = "Product 14",
                            Price = 50027.44m
                        },
                        new
                        {
                            Id = new Guid("bfe07b09-e343-47fa-ac03-fe5deac8a244"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8119),
                            Description = "The description of product 15",
                            ImgUri = "https://cdn.alza.cz/Foto/15",
                            Name = "Product 15",
                            Price = 97186.66m
                        },
                        new
                        {
                            Id = new Guid("73f25a32-6ff4-462f-91b0-dcde40da688b"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8128),
                            Description = "The description of product 16",
                            ImgUri = "https://cdn.alza.cz/Foto/16",
                            Name = "Product 16",
                            Price = 54623.56m
                        },
                        new
                        {
                            Id = new Guid("5516ba7c-f99e-4c4e-aca2-78e147e89c47"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8134),
                            Description = "The description of product 17",
                            ImgUri = "https://cdn.alza.cz/Foto/17",
                            Name = "Product 17",
                            Price = 20838.61m
                        },
                        new
                        {
                            Id = new Guid("e7feb64b-1861-4c47-8089-b0ac58f8c8ab"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8143),
                            Description = "The description of product 18",
                            ImgUri = "https://cdn.alza.cz/Foto/18",
                            Name = "Product 18",
                            Price = 6257.81m
                        },
                        new
                        {
                            Id = new Guid("713b7b55-a7b7-47f5-b311-0ba907030351"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8149),
                            Description = "The description of product 19",
                            ImgUri = "https://cdn.alza.cz/Foto/19",
                            Name = "Product 19",
                            Price = 58833.05m
                        },
                        new
                        {
                            Id = new Guid("4d10ad35-714f-42ba-a645-9a7166e93b96"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8156),
                            Description = "The description of product 20",
                            ImgUri = "https://cdn.alza.cz/Foto/20",
                            Name = "Product 20",
                            Price = 19348.98m
                        },
                        new
                        {
                            Id = new Guid("8b45cb7a-15f4-4fae-9804-80920ce90419"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8162),
                            Description = "The description of product 21",
                            ImgUri = "https://cdn.alza.cz/Foto/21",
                            Name = "Product 21",
                            Price = 58885.12m
                        },
                        new
                        {
                            Id = new Guid("43156284-4785-409e-83b7-b33951a474a6"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8168),
                            Description = "The description of product 22",
                            ImgUri = "https://cdn.alza.cz/Foto/22",
                            Name = "Product 22",
                            Price = 33662.44m
                        },
                        new
                        {
                            Id = new Guid("cf06c36e-6dd3-451a-a9bf-082ca6bb31c3"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8174),
                            Description = "The description of product 23",
                            ImgUri = "https://cdn.alza.cz/Foto/23",
                            Name = "Product 23",
                            Price = 96359.5m
                        },
                        new
                        {
                            Id = new Guid("ee5a456b-e82c-4314-92f4-8c04ccf4a0a0"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8183),
                            Description = "The description of product 24",
                            ImgUri = "https://cdn.alza.cz/Foto/24",
                            Name = "Product 24",
                            Price = 99182.22m
                        },
                        new
                        {
                            Id = new Guid("859d0c66-0c59-4a84-91c3-14bbd2b168b6"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8190),
                            Description = "The description of product 25",
                            ImgUri = "https://cdn.alza.cz/Foto/25",
                            Name = "Product 25",
                            Price = 11088.67m
                        },
                        new
                        {
                            Id = new Guid("fb2e2743-229f-4966-83c5-ae62c1212b27"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8196),
                            Description = "The description of product 26",
                            ImgUri = "https://cdn.alza.cz/Foto/26",
                            Name = "Product 26",
                            Price = 76283.36m
                        },
                        new
                        {
                            Id = new Guid("7d2c66c0-53f9-40c9-91da-0dd7314477f7"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8202),
                            Description = "The description of product 27",
                            ImgUri = "https://cdn.alza.cz/Foto/27",
                            Name = "Product 27",
                            Price = 49229.43m
                        },
                        new
                        {
                            Id = new Guid("b95c6661-23e8-4799-98b3-bca6a82b7791"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8209),
                            Description = "The description of product 28",
                            ImgUri = "https://cdn.alza.cz/Foto/28",
                            Name = "Product 28",
                            Price = 39954.35m
                        },
                        new
                        {
                            Id = new Guid("94f22ae2-e614-4b29-bf2f-bf3b3c2ab952"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8215),
                            Description = "The description of product 29",
                            ImgUri = "https://cdn.alza.cz/Foto/29",
                            Name = "Product 29",
                            Price = 26809.13m
                        },
                        new
                        {
                            Id = new Guid("e739097c-ee32-45b4-96e8-8854b3f55fbd"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8221),
                            Description = "The description of product 30",
                            ImgUri = "https://cdn.alza.cz/Foto/30",
                            Name = "Product 30",
                            Price = 21481.23m
                        },
                        new
                        {
                            Id = new Guid("7d9b7ce2-87d1-4a7b-9386-7b581ebe9e6d"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8227),
                            Description = "The description of product 31",
                            ImgUri = "https://cdn.alza.cz/Foto/31",
                            Name = "Product 31",
                            Price = 10252.2m
                        },
                        new
                        {
                            Id = new Guid("cdae1971-e111-424f-9371-11ee148e188d"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8235),
                            Description = "The description of product 32",
                            ImgUri = "https://cdn.alza.cz/Foto/32",
                            Name = "Product 32",
                            Price = 54380.63m
                        },
                        new
                        {
                            Id = new Guid("195d1f6c-2edc-46df-9b7f-fe9790a09b62"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8241),
                            Description = "The description of product 33",
                            ImgUri = "https://cdn.alza.cz/Foto/33",
                            Name = "Product 33",
                            Price = 57670.33m
                        },
                        new
                        {
                            Id = new Guid("a098b197-887e-45e7-a81e-845b093d7e25"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8289),
                            Description = "The description of product 34",
                            ImgUri = "https://cdn.alza.cz/Foto/34",
                            Name = "Product 34",
                            Price = 39886.25m
                        },
                        new
                        {
                            Id = new Guid("ff74cfe6-95db-41bf-8c66-0c399d387c16"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8295),
                            Description = "The description of product 35",
                            ImgUri = "https://cdn.alza.cz/Foto/35",
                            Name = "Product 35",
                            Price = 41872.33m
                        },
                        new
                        {
                            Id = new Guid("23c448e2-6b97-45aa-804a-f18afe087b7d"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8301),
                            Description = "The description of product 36",
                            ImgUri = "https://cdn.alza.cz/Foto/36",
                            Name = "Product 36",
                            Price = 86565.33m
                        },
                        new
                        {
                            Id = new Guid("c68e3ad9-9333-4f29-a26e-b4a936c2d67f"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8307),
                            Description = "The description of product 37",
                            ImgUri = "https://cdn.alza.cz/Foto/37",
                            Name = "Product 37",
                            Price = 65620.22m
                        },
                        new
                        {
                            Id = new Guid("61ed40d6-d664-4d3b-a128-8dcc171e644f"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8313),
                            Description = "The description of product 38",
                            ImgUri = "https://cdn.alza.cz/Foto/38",
                            Name = "Product 38",
                            Price = 34363.36m
                        },
                        new
                        {
                            Id = new Guid("4ab815af-cee7-461f-bd54-cfc57a7c85a1"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8320),
                            Description = "The description of product 39",
                            ImgUri = "https://cdn.alza.cz/Foto/39",
                            Name = "Product 39",
                            Price = 22550.16m
                        },
                        new
                        {
                            Id = new Guid("6e89381e-765a-48f0-8bb6-0823302f2740"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8329),
                            Description = "The description of product 40",
                            ImgUri = "https://cdn.alza.cz/Foto/40",
                            Name = "Product 40",
                            Price = 57489.36m
                        },
                        new
                        {
                            Id = new Guid("a3e537f8-433f-4ee2-a4ff-3a8cee2a8d21"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8335),
                            Description = "The description of product 41",
                            ImgUri = "https://cdn.alza.cz/Foto/41",
                            Name = "Product 41",
                            Price = 72401.78m
                        },
                        new
                        {
                            Id = new Guid("22a1bf10-a094-4c24-aa6b-65d1cd07aa04"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8341),
                            Description = "The description of product 42",
                            ImgUri = "https://cdn.alza.cz/Foto/42",
                            Name = "Product 42",
                            Price = 92021.63m
                        },
                        new
                        {
                            Id = new Guid("4efc7f03-083b-441c-bfdb-714f65df2180"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8347),
                            Description = "The description of product 43",
                            ImgUri = "https://cdn.alza.cz/Foto/43",
                            Name = "Product 43",
                            Price = 52021.6m
                        },
                        new
                        {
                            Id = new Guid("d16c7f2f-67e0-4635-a4d3-2abe85c347dd"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8354),
                            Description = "The description of product 44",
                            ImgUri = "https://cdn.alza.cz/Foto/44",
                            Name = "Product 44",
                            Price = 78567.54m
                        },
                        new
                        {
                            Id = new Guid("055a44da-792c-42cd-9069-5b4f56479447"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8360),
                            Description = "The description of product 45",
                            ImgUri = "https://cdn.alza.cz/Foto/45",
                            Name = "Product 45",
                            Price = 69898.22m
                        },
                        new
                        {
                            Id = new Guid("82cd7071-e7c0-46bb-9c72-1cae29d69b2c"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8366),
                            Description = "The description of product 46",
                            ImgUri = "https://cdn.alza.cz/Foto/46",
                            Name = "Product 46",
                            Price = 31761.29m
                        },
                        new
                        {
                            Id = new Guid("3be77be4-bd3c-4bcd-ac55-d43f2b13fb3c"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8373),
                            Description = "The description of product 47",
                            ImgUri = "https://cdn.alza.cz/Foto/47",
                            Name = "Product 47",
                            Price = 7187.54m
                        },
                        new
                        {
                            Id = new Guid("559dfd96-f1e5-4485-8e85-36a51f08a042"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8382),
                            Description = "The description of product 48",
                            ImgUri = "https://cdn.alza.cz/Foto/48",
                            Name = "Product 48",
                            Price = 21141.6m
                        },
                        new
                        {
                            Id = new Guid("d15caa39-ce75-4dcd-8f82-b28e36dfe5e4"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8388),
                            Description = "The description of product 49",
                            ImgUri = "https://cdn.alza.cz/Foto/49",
                            Name = "Product 49",
                            Price = 79471.55m
                        },
                        new
                        {
                            Id = new Guid("6418c027-f62d-496a-b675-2e8272ce0490"),
                            Created = new DateTime(2020, 11, 16, 14, 30, 44, 264, DateTimeKind.Local).AddTicks(8394),
                            Description = "The description of product 50",
                            ImgUri = "https://cdn.alza.cz/Foto/50",
                            Name = "Product 50",
                            Price = 45084.58m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
